AUTHC_CONFIG:
  account_lock_threshold: null
  preferred_algorithm: argon2
  hash_algorithms:
    argon2: {}
    bcrypt_sha256: {}
    sha256_crypt:
      default_rounds: 110000
      max_rounds: 1000000
      min_rounds: 1000
      salt_size: 16
  totp:
    mfa_dispatcher: null
    context:
      secrets:
        update_this_tag_with_unixepoch:  update_this_using_passlib.totp.generate_secret()

SECURITY_MANAGER_CONFIG:
  security_manager: yosai.core.NativeSecurityManager
  attributes:
    serializer: cbor
    realms:
      yosai.core.AccountStoreRealm:
        account_store: anchore_engine.subsys.auth.stores.basic.DbAccountStore
        #authc_verifiers: yosai.core.PasslibVerifier
        authc_verifiers: anchore_engine.subsys.auth.stores.verifier.SimpleVerifier
    cache_handler: anchore_engine.subsys.auth.util.caches.SimpleMemoryCache
    session_attributes: null

#REMEMBER_ME_CONFIG:
#    default_cipher_key: null

# These are essentially ignored, because sessions are disabled in the service itself
SESSION_CONFIG:
  session_timeout:
    absolute_timeout: 1800
    idle_timeout: 300
  session_validation:
    scheduler_enabled: false
    time_interval: 3600
